apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
  namespace: scd-project
  labels:
    app: k8s-demo
spec:
  type: NodePort
  selector:
    app: k8s-demo
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: scd-project
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # This creates a headless service